name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd ~/src/_username_/_app-name_
            git checkout main && git pull
            go test -v ./...
            ./script/ci-prod.sh

